services:
  api:
    restart: always
    container_name: volleyballturnier-backend
    build:
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    expose:
      - 3000
    networks:
      - proxy-network
      - backend-network
  mariadb:
    restart: always
    image: mariadb:10.7
    ports:
      - 33062:3306
    volumes:
      - db:/data
    env_file:
      - .env
    networks:
      - backend-network

volumes:
  db:

networks:
  proxy-network:
    external: true
  backend-network:
    driver: bridge